version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:11.1-alpine
        # 環境情報を追加
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=beauty-match_test
    # ディレクトリ情報を移動（こうしないとエラーになる）
    working_directory: ~/beauty-match
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}

      - run: # Ruby の依存関係をインストールします
          name: バンドルインストール
          command: |
            gem update --system
            gem install bundler

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      # DBのセットアップを修正
      - run:
          name: Database setup
          command: |
            bin/rails db:create db:schema:load --trace
            bin/rails db:migrate

      # run tests!
      # RSpecの実行も修正
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"

      # Save test results for timing analysis
      - store_test_results:
          path: test_results